"""adding speaker embeddings

Revision ID: 7038feafa4a4
Revises: d9d4f113c884
Create Date: 2026-01-14 15:59:06.491665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '7038feafa4a4'
down_revision: Union[str, None] = 'd9d4f113c884'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speaker_embeddings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recording_id', sa.String(length=36), nullable=False),
    sa.Column('speaker_label', sa.String(length=50), nullable=False),
    sa.Column('embedding_vector', Vector(dim=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speaker_embeddings_recording_id'), 'speaker_embeddings', ['recording_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_speaker_embeddings_recording_id'), table_name='speaker_embeddings')
    op.drop_table('speaker_embeddings')
    # ### end Alembic commands ###
