"""adding processing start time

Revision ID: d9d4f113c884
Revises: a1f269a0bcc1
Create Date: 2026-01-13 09:14:37.495854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9d4f113c884'
down_revision: Union[str, None] = 'a1f269a0bcc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recordings', sa.Column('processing_started_at', sa.DateTime(), nullable=True))
    op.alter_column('recordings', 'processing_status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_recordings_created_at'), table_name='recordings')
    op.drop_index(op.f('idx_recordings_status'), table_name='recordings')
    op.drop_index(op.f('idx_transcript_chunks_embedding_hnsw'), table_name='transcript_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_transcript_chunks_recording_id'), table_name='transcript_chunks')
    op.create_index(op.f('ix_transcript_chunks_recording_id'), 'transcript_chunks', ['recording_id'], unique=False)
    op.alter_column('transcripts', 'recording_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transcripts', 'recording_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_index(op.f('ix_transcript_chunks_recording_id'), table_name='transcript_chunks')
    op.create_index(op.f('idx_transcript_chunks_recording_id'), 'transcript_chunks', ['recording_id'], unique=False)
    op.create_index(op.f('idx_transcript_chunks_embedding_hnsw'), 'transcript_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_index(op.f('idx_recordings_status'), 'recordings', ['processing_status'], unique=False)
    op.create_index(op.f('idx_recordings_created_at'), 'recordings', ['created_at'], unique=False)
    op.alter_column('recordings', 'processing_status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.drop_column('recordings', 'processing_started_at')
    # ### end Alembic commands ###
